import { CliError } from "@wirecat/cli-core"
import type { CacheDatabase } from "./driver.js"
import { generatedMigrations } from "./sqlite/manifest.js"

export interface Migration {
  version: number
  /** The oldest schema version whose statements still work on a file at this version. */
  minCompatible: number
  statements: string[]
  /** Runs before the statements, inside the same transaction. */
  before?: (database: CacheDatabase, now: () => number) => void
}

/**
 * Every migration is generated by drizzle-kit and numbered in `sqlite/manifest.ts`. Version 1 creates the whole
 * schema. **A migration that has reached anyone's file is never edited.** After it: forward-only and additive —
 * no `DROP` and no rebuild of a base table, a new column is nullable or has a default, and every `INSERT` in the
 * store names its columns — so an older `tg` keeps writing to a file a newer `max` has migrated. Only a breaking
 * change raises `minCompatible`, and that is a major version of this package. The search indexes are derived and
 * may be dropped and rebuilt. Every version after the first gets a `version-N.test.ts` that opens a file at N-1.
 *
 * Times are epoch milliseconds: an integer sorts and ranges without a format to agree on.
 */
export const MIGRATIONS: Migration[] = generatedMigrations()

const HISTORY = `CREATE TABLE IF NOT EXISTS schema_migrations (
  version        INTEGER PRIMARY KEY,
  min_compatible INTEGER NOT NULL,
  applied_at     INTEGER NOT NULL
)`

const latest = (migrations: Migration[]): number => migrations.at(-1)?.version ?? 0

const fileState = (database: CacheDatabase): { version: number; minCompatible: number } => {
  const row = database
    .prepare("SELECT version, min_compatible FROM schema_migrations ORDER BY version DESC LIMIT 1")
    .get()
  return { version: Number(row?.version ?? 0), minCompatible: Number(row?.min_compatible ?? 0) }
}

/**
 * Brings the file up to this version, or opens a newer one it can still write to, or refuses.
 * Inside `BEGIN IMMEDIATE`, so two processes opening an old file at once migrate it once. A migration
 * that fails names `store reset`: without it the owner is stuck until a build that can migrate the file.
 */
export const migrate = (
  database: CacheDatabase,
  {
    migrations = MIGRATIONS,
    now = Date.now,
    command,
  }: { migrations?: Migration[]; now?: () => number; command?: string } = {},
): void => {
  const ours = latest(migrations)
  database.exec("BEGIN IMMEDIATE")
  try {
    database.exec(HISTORY)
    const file = fileState(database)
    if (file.version > ours && file.minCompatible > ours) {
      throw new CliError(
        "configuration_error",
        `the message store was written by a newer version (schema ${file.version}, needs at least ` +
          `${file.minCompatible}; this one speaks ${ours}) — upgrade this tool`,
      )
    }
    for (const migration of migrations) {
      if (migration.version <= file.version) continue
      migration.before?.(database, now)
      for (const statement of migration.statements) database.exec(statement)
      database
        .prepare("INSERT INTO schema_migrations (version, min_compatible, applied_at) VALUES (?, ?, ?)")
        .run(migration.version, migration.minCompatible, now())
    }
    database.exec("COMMIT")
  } catch (error) {
    database.exec("ROLLBACK")
    if (error instanceof CliError) throw error
    const cause = error instanceof Error ? error.message : String(error)
    throw new CliError(
      "configuration_error",
      `the message store could not be brought up to schema ${ours}: ${cause}. ` +
        `\`${command ? `${command} ` : ""}store reset\` takes a backup of it first, then starts an empty store`,
      { cause },
    )
  }
}
