import { writeFileSync } from "node:fs"
import { dropped, indexes, model } from "./spec.mjs"

const mdPath = process.argv[2] ?? new URL("../../docs/storage/schema.md", import.meta.url).pathname
const groups = model()
const all = groups.flatMap((g) => g.tables)
const base = all.filter((t) => !t.virtual)
const stats = {
  tables: base.length,
  indexes: all.length - base.length,
  added: all.filter((t) => t.status === "new").length,
  dropped: Object.keys(dropped).length,
}

const CONVENTIONS = [
  "Tables plural, snake_case. Primary key `id`. Foreign key `<singular>_id`. No `pk`, no `uid`.",
  "The source's own id is `external_id`; another thing's source id is `<thing>_external_id`.",
  "`created_at` and `updated_at` say when **our** row was saved and changed. Times of the world keep their names: `sent_at`, `joined_at`, `started_at`, `due_at`.",
  "`deleted_at` means gone at the source; sync never hard-deletes, only an owner command purges.",
  "Polymorphic associations: `<name>_type` text (the singular table name: `person`, `bot`, `email`) + `<name>_id` integer. Actors (who made or owns something) are `person` or `bot`.",
  "Searchable data gets its own column; `metadata` (JSON) holds only what is not searched.",
  "Booleans without `is_`. Times are epoch milliseconds, integers: they sort and range without a format to agree on.",
  "One search index per corpus: messages, emails, attachments, documents, notes, memories, meetings.",
  "Every foreign key and every polymorphic pair is indexed; listed under each table as *Indexes*.",
]

const flags = (col) =>
  [col.pk ? "PK" : "", col.notnull ? "not null" : "", col.unique ? "unique" : ""].filter(Boolean).join(", ")
const mdEsc = (s) =>
  String(s ?? "")
    .replace(/\|/g, "\\|")
    .replace(/\n/g, " ")

const md = [
  "# Store schema",
  "",
  "Every table of the shared store (tg, max, memo, zm) as its migrations create it. Generated by",
  "`pnpm schema:render` from `scripts/schema/spec.mjs`; `src/store/sqlite/schema.ts` and the hand-written SQL in",
  "`drizzle/` must agree with it. `pnpm schema:check` fails when they do not, and `src/store/sqlite/schema.test.ts`",
  "checks every table and column of a new store against this page.",
  "",
  `${stats.tables} tables, ${stats.indexes} full-text indexes; ${stats.added} new, ${stats.dropped} of today's dropped or merged.`,
  "Status: **new** — added; **changed** — merged, split or reshaped; **renamed** — naming rules and timestamps only; **kept** — as today.",
  "",
  "## Conventions",
  "",
  ...CONVENTIONS.map((x) => `- ${x}`),
  "",
  ...groups.flatMap((g) => [
    `## ${g.title}`,
    "",
    g.blurb,
    "",
    ...g.tables.flatMap((t) => {
      const head = [
        `### \`${t.name}\` — ${t.status}${t.was ? ` (was \`${t.was}\`)` : ""}`,
        "",
        t.doc ? `${t.doc}` : "",
        t.note ? `\n*Change:* ${t.note}` : "",
        "",
      ]
      if (t.virtual) return [...head, "```sql", t.sql, "```", ""]
      const rows = t.cols.map(
        (col) =>
          `| \`${col.name}\`${col.was ? ` ← \`${col.was}\`` : ""} | ${col.type} | ${flags(col)} | ${col.ref ? `→ \`${col.ref}\`` : ""} | ${mdEsc(col.note)} |`,
      )
      const keys = [...(t.keys ?? []), ...indexes(t)]
      return [
        ...head,
        "| Column | Type | Constraints | References | Meaning |",
        "|---|---|---|---|---|",
        ...rows,
        "",
        ...(keys.length ? [`*Keys and indexes:* ${keys.map((k) => `\`${k}\``).join(", ")}`, ""] : []),
      ]
    }),
  ]),
  "## Dropped or merged",
  "",
  "| Today | Where it goes |",
  "|---|---|",
  ...Object.entries(dropped).map(([k, v]) => `| \`${k}\` | ${v} |`),
  "",
].filter((line, i, a) => !(line === "" && a[i - 1] === ""))

writeFileSync(mdPath, `${md.join("\n").trimEnd()}\n`)
